import hashlib
import os
import time
import datetime

BUF_SIZE = 65536  # lets read stuff in 64kb chunks!

directory_in_str = "data"
directory = os.fsencode(directory_in_str)

for file in os.listdir(directory):
    sha2 = hashlib.sha256()
    filename = os.fsdecode(file)
    filename = directory_in_str+"/"+filename
    start_time =datetime.datetime.now()
    with open(filename, 'rb') as f:
        while True:
            data = f.read(BUF_SIZE)
            if not data:
                break
            sha2.update(data)
    end_time = datetime.datetime.now()
    time_taken = end_time - start_time
    print("File Name: "+filename)
    print("HashCode Generated by SHA-256: {0}".format(sha2.hexdigest()))
    print("Time Taken: "+str(time_taken.total_seconds() * 1000)+" ms")
    print()
